### ISSUE TITLE
ERROR in AppInsightsModule is not an NgModule

### ISSUE THREAD

**Issue by Walgermo** [harry671003/ng2-appinsights#2]
In the latest version 0.3.0 the appinsights.module.d.ts is almost empty, is this intended?

![image](https://cloud.githubusercontent.com/assets/1300710/22290814/50074ad0-e303-11e6-85be-fe09996941b6.png)

When i try to setup as in the [example ](https://github.com/harry671003/ng2-appinsights/tree/master/e2e/app) i get this error.

**Comment by harry671003** [comment]
@Walgermo What is the error you are getting? Could you be more specific?

**Comment by stuarthallows** [comment]
One consequence is that AOT compilation fails. For example when I run...

`"node_modules/.bin/ngc" -p tsconfig-aot.json`

I see the error...

`Unexpected value 'AppInsightsModule in D:/Code/my-app/node_modules/ng2-appinsights/appinsights/appinsights.module.d.ts' imported by the module 'AppModule in D:/Code/my-app/src/app/app.module.ts'`

and when I do an `ng serve` I see `ERROR in AppInsightsModule is not an NgModule`.

![image](https://cloud.githubusercontent.com/assets/1193012/22778782/0dd94e9a-ef08-11e6-9a62-fe744e736006.png)

**Comment by ruimserrano** [comment]
Yes! would be nice to have an upgrade to make it AOT compatible.

**Comment by pradeep14** [comment]
Hi, 
I got this  **Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3997/ng2-appinsights** when ever I added the below line of code`import { AppInsightsModule } from 'ng2-appinsights';` even I mention the latest version of ng2-appinsights in package.json.

can you please see [this link](http://stackoverflow.com/questions/42344660/error-systemjs-xhr-error-404-not-found-loading-ng2-appinsights/) for more information of error what I got.

-Pradeep

**Comment by stuarthallows** [comment]
BTW, the `ERROR in AppInsightsModule is not an NgModule` error also occurs on creating a brand new Angular CLI project and then simply adding ng2-appinsights.

**Comment by harry671003** [comment]
Hi Everyone,

Published the version 0.5.0 of the package. This issue is fixed. 
Can you verify @stuarthallows  @Walgermo ?
