### ISSUE TITLE
this.appInsights.downloadAndSetup is not a function 

### ISSUE THREAD

**Issue by shawnrmoss** [harry671003/ng2-appinsights#7]
Ive followed the installation steps.  

Imported into my app.module. Brought the service into my component

But when I call : 
this.appInsightsService.Init({
            instrumentationKey: 'XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
            verboseLogging: true
        });

I get this error:  this.appInsights.downloadAndSetup is not a function

**Comment by samidabeast** [comment]
I am currently having this issue. How did you fix it?
