### ISSUE TITLE
Request: Would love to have support for @angular/core 4.0.0

### ISSUE THREAD

**Issue by Perroquiet** [harry671003/ng2-appinsights#8]
Installed this package with the latest Angular 4 release. and got a warning:

`npm WARN ng2-appinsights@0.5.0 requires a peer of @angular/core@^2.4.0 but none was installed.`

**Comment by harry671003** [comment]
@Perroquiet This is just a warning. Is the functionality breaking?

**Comment by Perroquiet** [comment]
@harry671003 Its still working.
