### ISSUE TITLE
ng2-appinsights rename/ update to angular 4

### ISSUE THREAD

**Issue by crh225** [harry671003/ng2-appinsights#9]
Do you plan on renaming ng2-appinsights, and plan on upgrading to angular 4?

**Comment by harry671003** [comment]
@crh225 The current version will work with angular 4.

**Comment by crh225** [comment]
@harry671003 yes it does work with angular 4; however, ng2-appinsignts has a peer dependency of angular 2. Everytime I run npm install or yarn; it give me warnings that this package has peer dependancy of outdated angular.

**Comment by crh225** [comment]
![image](https://cloud.githubusercontent.com/assets/19475195/25234717/8eebebce-25a8-11e7-8ddc-9d6033960986.png)

**Comment by dandax** [comment]
A simple fix would be to just update the dependencies like this
```
    "@angular/common": "^2.4.9||^4.0.0",
    "@angular/compiler": "^2.4.9||^4.0.0",
    ...
```

**Comment by jordan112** [comment]
PR for this version bump.  https://github.com/harry671003/ng2-appinsights/pull/10
